### ISSUE TITLE
No longer working with most recent IntelliJ IDEA

### ISSUE THREAD

**Issue by factotvm** [Lonami/uniffi-dl#9]
Thanks for the project, I was pleasantly surprised to be prompted to install it. And, well, now I'm feeling at a loss to be without it. 😄 

I've never created a plugin, nor looked at the documentation, but it seems like the issue is with this line: https://github.com/Lonami/uniffi-dl/blob/master/gradle.properties#L3

As the most recent version of IntelliJ IDEA is 243.*, I believe that's the problem.

Thanks so much again for the project, and let me know if I can help.

**Comment by Lonami** [comment]
I'm not actively using the plugin myself, but if you send a pull request similar to #8, I'll happily publish a new version.

**Comment by Lonami** [comment]
@julioromano @ovitrif and @factotvm - would any of you be willing to be made maintainers on the repository? I keep receiving emails about it, but I can't really keep up with every single new version of IntelliJ:

> ![Image](https://github.com/user-attachments/assets/5e6a5e15-5f81-4983-bc72-0095a56fd552)
> 
> Hello Lonami E,
> 
> We noticed that due to a limited Until range, the following plugins will not be compatible with the upcoming IDE version (2025.1):
> 
> * [Uniffi-DL](https://plugins.jetbrains.com/plugin/20527-uniffi-dl) 
> 
> The EAP version was just released, so you have time to address the issue by uploading a new version with a higher or unlimited 'Until Build' setting.
> 
> We kindly suggest that you adjust the compatibility range to enable current users to continue enjoying the functionalities of your plugin without any interruptions.
> 
> Moreover, updating the compatibility settings will also make your plugin discoverable to new users who are exploring the latest version of our IDE.
> 
> Please feel free to reach out if you have any questions or require further assistance.
> 
> You can unsubscribe from future notifications about the specific plugin on the plugin page, by clicking the subscription button (bell) in the top right-hand corner of the plugin page.
> 
> Best regards,
> JetBrains Marketplace Team

**Comment by julioromano** [comment]
Thanks for thinking about me but unfortunately I've switched jobs and am no longer working with Rust nowadays, therefore I couldn't commit any bandwidth to this.

**Comment by ovitrif** [comment]
> […] [@ovitrif](https://github.com/ovitrif) […] - would any of you be willing to be made maintainers on the repository? I keep receiving emails about it, but I can't really keep up with every single new version of IntelliJ:

Hey @Lonami 
Happy to become a maintainer of this repo, I can take care of the maintenance upgrades to keep it in sync with the latest IntelliJ IDEs versions.

Noticed the plugin is also referenced in UniFFI's [README.md](https://github.com/mozilla/uniffi-rs/blob/main/README.md), it would be nice to have it up-to-date for the community.

**Comment by Lonami** [comment]
Thanks for stepping up @ovitrif, do you prefer all rights on this repo or should I transfer ownership outright?

**Comment by ovitrif** [comment]
> Thanks for stepping up [@ovitrif](https://github.com/ovitrif), do you prefer all rights on this repo or should I transfer ownership outright?

Thanks! Yes, I’d be happy to take over ownership of the repo.
You can transfer it to @ovitrif, please 🙏🏻 .

**Comment by Lonami** [comment]
One thing I'm concerned about is of users updating without knowing there's been an owner change.

It seems we might need some back and forth with IntelliJ support https://intellij-support.jetbrains.com/hc/en-us/community/posts/18039165001874-How-to-transfer-IntelliJ-plugin-ownership but, I'd also like to know, are your plans with uniffi-dl to simply keep up with upgrades to support the latest IDEs or do you plan to push other features?

**Comment by ovitrif** [comment]
> One thing I'm concerned about is of users updating without knowing there's been an owner change.
> 
> It seems we might need some back and forth with IntelliJ support https://intellij-support.jetbrains.com/hc/en-us/community/posts/18039165001874-How-to-transfer-IntelliJ-plugin-ownership but, I'd also like to know, are your plans with uniffi-dl to simply keep up with upgrades to support the latest IDEs or do you plan to push other features?

Only going to keep up with IDE upgrades, I don't really have the time to focus on feature development.

Surely, I also plan to address any issues that are getting filed in the repo, hopefully by resolving them in a timely manner.

---

If it makes things easier from your PoV, please note that I’m fine with whichever option is easiest for you, just adding @ovitrif as a collaborator/maintainer would work for me as well 👍🏻.

**Comment by Lonami** [comment]
So I have taken a look at your profile's bio, and I'm generally wary of all things related to cryptocurrencies.

I do remember you've previously helped with updating this repository (which is appreciated), but perhaps it's easier / best that we keep that workflow longer and see how it goes? That way there'll be an extra pair of eyes reviewing the work.

If I knew which files to update and how to update them, I could probably do it whenever people report that the latest version is no longer compatible, too.

**Comment by ovitrif** [comment]
> So I have taken a look at your profile's bio, and I'm generally wary of all things related to cryptocurrencies.

Yes, it's not a hidden fact: I work in Bitcoin. You can see the repos I'm mostly active in, that is my daily job, it's for a Bitcoin-only wallet.

No, I am not a crypto guy, never will be, and I am also bombarded with spam from fresh repos made with only one purpose: to lure naive people to their new crypto scam.

With all this being said, you can also see on my profile that I am a real person, using my real name, etc; so this should give you a pretty good picture of what kind of guy I am.

Aside from my main job, I contribute to open source projects randomly, it only has to do with whether I need an improvement to a repo, then I am more likely to contribute.

That's how I found this repo in the first place, all my Rust-literate colleagues were deep into UniFFI and stuff, I barely knew how to approach UDL, so I needed a syntax highlighter to help me in the IDEs where I feel comfortable: IntelliJ IDEA, Android Studio and RustRover.

If you suspect I'm a "crypto boi" after one year of not spamming you in any way, and simply doing my contributor job that one time last year, never heard from me again, and now seeing there's still a struggle to keep this plugin up-to-date and seeing there is demand from the community, offering to keep maintaining it, than I am respectfully stepping away.

I don't have anything to gain from this, but be aware, I do not like to be categorized and labelled from a pure stance of ignorance.

Bitcoin is totally different from all the other cryptocurrencies, and bitcoiners have a totally different reputation than crypto bois.

Thanks for the offer, but I'm much less interested now.

FWIW, please don't forget that I could've forked the repo at any time and could've published another plugin to compete with this one. The fact that I didn't should tell you everything you need to know about whether to trust me or not.

**Comment by Lonami** [comment]
I wasn't trying to imply that, but I have moderated large groups for a long time and the crypto spam is completely out of control, hence my reason to be wary. Unfortunately it becomes hard to trust as a default, and I wouldn't want users to install a version owned entirely by anyone else without the users being aware (as I have made a similar mistake to this before.)

I do understand not wanting to keep up with PRs if there's nothing to "gain" though (full ownership of the repository as part of the portfolio, any GitHub stars, etc.)

So for now this repository and plugin release will likely stay as-is until someone has a need to update it or use a fork.

**Comment by factotvm** [comment]
I'm back to wishing this were in place. I've never done any JetBrains plugin authoring, but I asked Copilot for a GitHub Actions that would allow easy publishing. However, as I asked questions, I learned that `untilBuild` isn't required (it was in old versions). What if it was just omitted? In the words of Claude Opus:

> Looking at uniffi-dl, it appears to be a language support plugin that likely doesn't depend on volatile internal APIs. We can simply remove the untilBuild constraint entirely.

What do you think?

For the alternative approach, here's the action:

<details>
<summary><kbd>github/workflows/publish.yml</kbd></summary>

```yaml

name: Publish Plugin

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Plugin version (e.g., 0.3.4)'
        required: true
        type: string
      sinceBuild:
        description: 'Minimum IDE build (e.g., 242)'
        required: true
        default: '242'
        type: string
      ideaVersion:
        description: 'IDE version for building (e.g., 2024.2)'
        required: true
        default: '2024.2'
        type: string

jobs:
  publish:
    name: Build and Publish Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Update gradle.properties
        run: |
          cat > gradle. properties << EOF
          ideaVersion=${{ inputs.ideaVersion }}
          sinceBuild=${{ inputs. sinceBuild }}
          EOF

      - name: Update plugin version in build. gradle. kts
        run: |
          sed -i 's/version = "[^"]*"/version = "${{ inputs.version }}"/' build. gradle.kts

      - name: Build plugin
        run: ./gradlew buildPlugin

      - name: Verify plugin
        run: ./gradlew verifyPlugin

      - name: Sign plugin
        env:
          CERTIFICATE_CHAIN: ${{ secrets.CERTIFICATE_CHAIN }}
          PRIVATE_KEY: ${{ secrets. PRIVATE_KEY }}
          PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}
        run: ./gradlew signPlugin

      - name: Publish plugin
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        run: ./gradlew publishPlugin

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: uniffi-dl-${{ inputs. version }}
          path: build/distributions/*. zip
```

</details>
